[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb-led-scoreboard-espn-sports"
version = "0.1.0"
description = "NFL/NHL/NBA/NCAAF/NCAAB/EPL scoreboard plugins backed by ESPN's public scoreboard API"
dependencies = ["Pillow>=10.0.1,<12.0.0"]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'bullpen.mlbled.plugin']
"nfl" = "mlb_led_scoreboard_espn_sports:load_nfl"
"nhl" = "mlb_led_scoreboard_espn_sports:load_nhl"
"nba" = "mlb_led_scoreboard_espn_sports:load_nba"
"ncaaf" = "mlb_led_scoreboard_espn_sports:load_ncaaf"
"ncaab" = "mlb_led_scoreboard_espn_sports:load_ncaab"
"epl" = "mlb_led_scoreboard_espn_sports:load_epl"
