[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb-led-scoreboard-game-menu"
version = "0.1.0"
description = "Game-select menu shown when entering the LED scoreboard's game area"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'bullpen.mlbled.plugin']
"game_menu" = "mlb_led_scoreboard_game_menu:load"
